config/routes.rb
Rails.application.routes.draw do
    resources :members
    root 'members#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
 # validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
    def index
        if session[:flag] === 2
            flash[:success] = '新規登録に成功しました'
        elsif session[:flag] === 4
            flash[:success] = '更新に成功しました'
        elsif session[:flag] === 5
            flash[:success] = '削除に成功しました'
        end
        session[:flag] = nil
        @members = Member.all
    end
    def new
        @member = Member.new
        session[:flag] = 1
    end
    def create
        errors = []
        if member_params[:name] === ''
            errors << "名前を入力してください"
        end
        if member_params[:yomi] === ''
            errors << "読み仮名を入力してください"
        end
        if member_params[:phone] === ''
            errors << "電話番号を入力してください"
        elsif /^[0-9]{3}-[0-9]{4}-[0-9]{4}$/ !~ member_params[:phone]
            errors << "電話番号は、xxx-xxxx-xxxx　で入力ください"
        end
        
        if errors.count === 0
            @member = Member.new(member_params)
            @member.save
            session[:flag] = 2
        end
        session[:error] = errors
        redirect_to root_path
    end
    def edit
        @member = find_by_id
        session[:flag] = 3
    end
    def update
        @member = find_by_id
        errors = []
        if member_params[:name] === ''
            errors << "名前を入力してください"
        end
        if member_params[:yomi] === ''
            errors << "読み仮名を入力してください"
        end
        if member_params[:phone] === ''
            errors << "電話番号を入力してください"
        elsif /^[0-9]{3}-[0-9]{4}-[0-9]{4}$/ !~ member_params[:phone]
            errors << "電話番号は、xxx-xxxx-xxxx　で入力ください"
        end
        
        if errors.count === 0
            @member.update(member_params)
            session[:flag] = 4
        end
        session[:error] = errors
        redirect_to root_path
    end
    def destroy
        #p 'ここ! destroy'
        @member = find_by_id
        @member.destroy
        session[:flag] = 5
        redirect_to root_path
    end
    private 
    def member_params
        params.require(:member).permit(:name, :yomi, :phone)
    end
    def find_by_id
        Member.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhoneBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<style>
    table, tr{
        border: solid 1px;
        margin: 0 auto;
    }
    th, td{
        border: solid 1px;
        padding: 5px;
        text-align: center;
        width: 15%;
        margin: 0 auto;
    }
    h1{
        width: 100%;
        color: red;
        text-align: center;
        
    }
</style>
<% 
  if session[:flag] === 1
    @message = '新規登録'
  elsif session[:flag] === 3
    @message = '更新'
  end
%>
<%= form_for @member do |f| %>
    <table>
        <tr>
            <td>
                <%= f.label :name, "名前" %>
            </td>
            <td>
                <%= f.text_field :name %>
            </td>
        </tr>
        <tr>
            <td>
                <%= f.label :yomi, "読み仮名" %>
            </td>
            <td>
                <%= f.text_field :yomi %>
            </td>
        </tr>
        <tr>
            <td>
                <%= f.label :phone, "電話番号" %>
            </td>
            <td>
                <%= f.text_field :phone, placeholder:'xxx-xxxx-xxxx' %>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <%= f.submit "#{@message}" %>
            </td>
        </tr>
    </table>
<% end %>

app/views/members/edit.html.erb
<h1>編集</h1>
<%= render "form" %>
<p>
    <%= link_to "一覧に戻る", root_path %>
</p>


    

app/views/members/index.html.erb
<% if @members.count == 0 %>
 <p>データはまだありません</p>
<% else %>
<style>
    table, tr{
        border: solid 1px;
        margin: 0 auto;
    }
    th, td{
        border: solid 1px;
        padding: 5px;
        text-align: center;
        width: 15%;
        margin: 0 auto;
    }
    h1{
        width: 100%;
        color: red;
        text-align: center;
        
    }
    .error{
        color: red;
        background-color: pink;
        width: 30%;
        padding: 3px;
        padding-left: 10px;
        margin-bottom: 5px;
    }
</style>
<%= flash[:success] %>
<ul>
    <% session[:error].each do |error| %>
        <li class="error"><%= error %></li>
    <% end %>
</ul>
    
<% session[:error] = []
    flash[:success] = ''
%>

<h1>電話帳</h1>
<table>
    <tr>
        <th>ID</th>
        <th>名前</th>
        <th>読み仮名</th>
        <th>電話番号</th>
        <th>編集</th>
        <th>削除</th>
    </tr>
    <% @members.each do |member| %>
    <tr>
        <td><%= member.id %></td>
        <td><%= member.name %></td>
        <td><%= member.yomi %></td>
        <td><%= member.phone %></td>
        <td><%= link_to '編集', edit_member_path(id:member.id) %></td>
        <td><%= link_to '削除', member_path(id:member.id), method: :delete, data: {confirm: "本当に削除しますか？"} %></td>
    </tr>
     <% end %>
    
</table>
 
<% end %>
<p>
    <%= link_to "新規登録", new_member_path%>
</p>

app/views/members/new.html.erb
<h1>新規電話帳登録</h1>
<%= render "form" %>
<p>
    <%= link_to "一覧に戻る", root_path %>
</p>


    